apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: directus-ingress
  namespace: mineral-museum
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "200"
    traefik.ingress.kubernetes.io/router.middlewares: mineral-museum-stripprefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /minerals
            pathType: Prefix
            backend:
              service:
                name: directus
                port:
                  number: 8055
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: mineral-museum
spec:
  stripPrefix:
    prefixes:
      - /minerals
