apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  rules:
    - http:
        paths:
          - path: /home-assistant
            pathType: Prefix
            backend:
              service:
                name: home-assistant-root
                port:
                  number: 80
