apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.priority: "100"
    traefik.ingress.kubernetes.io/router.middlewares: home-assistant-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: home-assistant-stripprefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /home-assistant
            pathType: Prefix
            backend:
              service:
                name: home-assistant-root
                port:
                  number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: home-assistant
spec:
  stripPrefix:
    prefixes:
      - /home-assistant
